
spring:
  config:
    activate:
      "on-profile": test  
  datasource:
    url: "jdbc:h2:mem:metamorfose_test"
    username: sa
    password: password
    "driver-class-name": org.h2.Driver
  
  jpa:
    hibernate:
      "ddl-auto": "create-drop"  
    "show-sql": true            
    properties:
      hibernate:
        "format_sql": true     
        dialect: org.hibernate.dialect.H2Dialect
    "open-in-view": false      
  
  h2:
    console:
      enabled: false

app:
  jwt:
    secret: "test-secret-key-for-testing-purposes-only-must-be-long-enough"
    expiration: 3600000

logging:
  level:
    "com.metamorfose.backend": DEBUG   
    "org.springframework.security": WARN 
    "org.hibernate.SQL": DEBUG         